devstack_repo: 'git://github.com/taoh/devstack.git'
devstack_branch: master
offline: no
reclone: no
git_base: 'git://github.com'
# comma delimited list of image urls
image_url: 'http://download.cirros-cloud.net/0.3.1/cirros-0.3.1-x86_64-uec.tar.gz'
